version: '3'
services:
  db:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
  api:
    build: ./api
    environment:
      - HOST=localhost
      - PORT=80
      - USERNAME=admin
      - DBUSER=root
      - DBPASS=password
      - DBCOLLECTION=eureukra
      - DBHOST=db
      - DBPORT=27017
      - JWT_SECRET=jwtsecret
      - JWT_EXPIRES=1h
    depends_on:
      - db
    ports:
      - 80:80
      - 3000:3000
  front:
    build: ./front
    depends_on: 
      - api
    ports:
      - 4200:4200


